### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by sjuvonen** [UshakovVasilii/gnome-shell-extension-redmine-issues#3]
Seems to me that this extensions always sorts the entries by their ID and therefore ignores what is defined in the API query. It would be nice if sorting was controlled by the query, so we could change it then.

**Comment by UshakovVasilii** [comment]
Issues can be added from different filters or manually. So we cannot use sorting from API query.
But I'll add setting to sort issues by specific field.
Thank you!
