### ISSUE TITLE
Not working on gnome 3.32

### ISSUE THREAD

**Issue by mickbad** [UshakovVasilii/gnome-shell-extension-redmine-issues#7]
Hello,

A useful extension but doesn't work on the last gnome api

Could you please update?

**Comment by mickbad** [comment]
thanks :)

**Comment by mickbad** [comment]
Thanks, works fine :)

**Comment by belcerca** [comment]
Thank you @UshakovVasilii . Your extension is incredibly useful and it was annoying that the extensions.gnome.org one stopped working when I updated my desktop to Fedora 30.

**Comment by UshakovVasilii** [comment]
Great, I'll update extension on extensions.gnome.org
